Add solution for fp2
YJorge/study pull request #3
Opened 2021-04-13 16:25 UTC by YJorge

2021-04-14 10:05 UTC, Andrew8xx8 requested changes

2021-04-14 10:05 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        for i in self
`each` нужно реальзовать используя рекурсию

2021-04-14 10:05 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        if acc.nil?
`reduce` нужно реализовать используя рекурсию

2021-04-14 10:33 UTC, YJorge commented on test/exercise/fp2/solution.rb
> +        if acc.nil?
то есть нельзя брать my_each за основу? в ней же будет рекурсия

2021-04-19 10:21 UTC, Andrew8xx8 approved these changes

2021-04-19 14:05 UTC, merged